version: '3.8'

services:
  ibmmq:
    image: ibmcom/mq:latest
    container_name: ibmmq
    ports:
      - "1414:1414"  # Port MQ
      - "9443:9443"  # Port console web
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
      - MQ_ADMIN_PASSWORD=passw0rd
      - MQ_APP_PASSWORD=passw0rd
    volumes:
      - qm1data:/mnt/mqm
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1414/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  qm1data: 